//
//  Boss.swift
//  ArticlesProject
//
//  Created by Cristian Bermudez Martinez on 26/2/24.
//

import Foundation

struct Boss: Identifiable {
  var id = UUID()
  var name: String
  var author: String
  var difficulty: Int
  var excerpt: String
  var image: String
  var content: String
  var url: String
}

#if DEBUG

let bosses = [
  Boss(name: "Margit, The Fell Omen", author: "Elden Ring Wiki", difficulty: 3, excerpt: "Margit, the Fell Omen is a Great Enemy Boss in Elden Ring. This is an optional boss as players don't need to defeat him to advance in Elden Ring, though they do need to defeat Margit to advance to Stormveil Castle.", image: "margit", content: "Margit, the Fell Omen is a Great Enemy Boss in Elden Ring. This is an optional boss as players don't need to defeat him to advance in Elden Ring, though they do need to defeat Margit to advance to Stormveil Castle.\nMargit, the Fell Omen is found in Stormhill when players attempt to approach Stormveil Castle. A non-boss variant can be found later again when approaching a stationary enemy slightly southwest of the Outer Wall Battleground Site of Grace in the Capital Outskirts. Margit stands in the Tarnished's way to prevent them from approaching the Elden Ring, though his motivations are only explained in a later encounter.\nTake the path north from Stormhill Shack and turn left at the fork, curving back south up a hill full of Godrick Soldiers. You'll need to either fight your way through these soldiers or run past them to reach the Castleward Tunnel Site of Grace, which is just in front of the boss door for Margit, the Fell Omen.", url: "https://eldenring.wiki.fextralife.com/Margit,+The+Fell+Omen"),
  Boss(name: "Godrick The Grafted", author: "Elden Ring Wiki", difficulty: 2, excerpt: "Godrick the Grafted, also known as Godrick the Golden, is a Demigod Boss in Elden Ring. This Elden Ring Godrick the Grafted Guide features boss locations, tips, strategies and videos on how to defeat Godrick easily, as well as boss stats and lore for Godrick. Bosses are unique and challenging Enemies that can be encountered all over the Lands Between. Shardbearers drop their own unique Great Rune and Remembrance capable of being transformed into powerful Weapons, Spells, Ashes of War, and Talismans for the player.", image: "godrick", content: "Godrick the Grafted is the ruler of Stormveil Castle, and is one of the first demigods and shardbearers that players can fight. He is a descendant of Godfrey and thus born of the golden lineage, but Gideon and Kenneth Haight believe him to be weak and unworthy to rule. Much of Godrick's power comes from the arms and legs of soldiers he's grafted onto himself, and especially the dragon head grafted onto his left arm during the second phase of his fight. His knights and soldiers wear armor that bears emblems of the golden lineage: a two-headed war-axe and the beast regent, Serosh.\nGodrick is an optional boss, and doesn't need to be defeated in order to advance in Elden Ring. You can advance to Liurnia of the Lakes without defeating him by following the path north from Stormhill Shack, then dropping down to the west from the broken bridge and walking along the outside of the castle. However, Godrick is a shardbearer, and two of the four available shardbearers must be defeated before entering Leyndell, Royal Capital.", url: "https://eldenring.wiki.fextralife.com/Godrick+the+Grafted"),
  Boss(name: "Red Wolf of Radagon", author: "Elden Ring Wiki", difficulty: 2, excerpt: "Red Wolf of Radagon is a Great Enemy Boss in Elden Ring. This giant red wolf wields sorceries and guards the found in the Grand Library of Raya Lucaria Academy.", image: "redwolf", content: "This is an optional boss as players don't need to defeat it to advance in Elden Ring, though they do need to defeat it to advance further in Raya Lucaria Academy and to achieve a certain ending.\nLesser Red Wolf of Radagon is the normal enemy form of this boss. Red Wolf of the Champion is another variant of this boss.\nHead out the door south of the Schoolhouse Classroom Site of Grace and along the corridor past several Glintstone Sorcerers. Once you get into the next room, turn west and head up both flights of stairs, then head east down the hallway to the fog gate leading to Red Wolf of Radagon.", url: "https://eldenring.wiki.fextralife.com/Red+Wolf+of+Radagon"),
  Boss(name: "Rennala, Queen of the Full Moon", author: "Elden Ring Wiki", difficulty: 3, excerpt: "Rennala, Queen of the Full Moon is a Legend Boss in Elden Ring. Though not a demigod, Rennala is one of the shardbearers who resides in the Academy of Raya Lucaria.", image: "rennala", content: "Rennala is a powerful sorceress, head of the Carian Royal family, and erstwhile leader of the Academy. Rennala is an optional boss, and doesn't need to be defeated in order to advance in Elden Ring. However, she is a shardbearer, and two of the four available shardbearers must be defeated before entering Leyndell, Royal Capital. In addition, she must be defeated to achieve a certain ending.\nOnce defeated, Rennala becomes a friendly NPC who can be used to reassign your character's stats.\nRennala, Queen of the Full Moon can be found after taking the elevator of the Raya Lucaria Academy.", url: "https://eldenring.wiki.fextralife.com/Rennala+Queen+of+the+Full+Moon"),
  Boss(name: "Leonine Misbegotten", author: "Elden Ring Wiki", difficulty: 2, excerpt: "This misbegotten is a feral humanoid with bestial features and a thick, crimson mane. It wields a large greatsword and is found at the end of Castle Morne.", image: "leonine", content: "This individual has stolen the treasured sword of Castle Morne, the one Edgar promised to protect. He is summonable for this fight if his and Irina's questline have been progressed to a certain point.\nThis is an optional boss as players are not required to defeat it to advance. The Leonine Misbegotten is extremely aggressive and it may be difficult to find openings to attack it. You will find yourself rolling most of the time in order to create distance as a ranged character, or as an alternative to Guarding as blocking it's attacks will deplete your Stamina quickly. It drops the Grafted Blade Greatsword when defeated.\nBosses are unique and challenging Enemies that can be encountered all over the Lands Between. Great Enemy bosses can drop unique Spirit Ashes, Weapons, Spells, and other various Items.\nLesser Misbegotten Warrior is the normal enemy form of this boss. Other variants of this boss appear in the Crucible Knight and Misbegotten Warrior, Perfumer Tricia and Misbegotten Warrior, and Misbegotten Crusader boss fights.", url: "https://eldenring.wiki.fextralife.com/Leonine+Misbegotten"),
  Boss(name: "Ancestor Spirit", author: "Elden Ring Wiki", difficulty: 2, excerpt: "Ancestor Spirit is a Great Enemy Boss in Elden Ring. This animated carcass of a deer-like creature is encountered in the Hallowhorn Grounds found in Siofra River.", image: "ancestor", content: "This is an optional boss, as players don't need to defeat it in order to advance in Elden Ring.\nAncestor Spirit is found in an isolated arena accessible from Siofra River. To access it, you must light all eight obelisks by the stairs to the Hallowhorn Grounds east of the Siofra River Bank Site of Grace. When you've done so, the deer carcass at the back of the temple will glow and you can interact with it to teleport just outside the boss's arena. Walk through the fog gate to fight the boss.", url: "https://eldenring.wiki.fextralife.com/Ancestor+Spirit"),
  Boss(name: "Starscourge Radahn", author: "Elden Ring Wiki", difficulty: 5, excerpt: "Starscourge Radahn is a Legend Boss in Elden Ring. Starscourge Radahn is heralded as one of the mightiest living demigods, having fought Malenia the Severed to a standstill during the war of the Shattering.", image: "radahn", content: "However, his resulting affliction with the Scarlet Rot caused him to be driven to insanity, crippling him and reducing him to a state of feral rage. He is located in Caelid, where he can be accessed from Redmane Castle after activating the Radahn Festival by progressing far enough in Ranni's questline, or activating any site of grace in Altus Plateau.\nRadahn is an optional boss, and doesn't need to be defeated to advance Elden Ring's main storyline. However, he is a shardbearer, and two of the four available shardbearers must be defeated before entering Leyndell, Royal Capital.", url: "https://eldenring.wiki.fextralife.com/Starscourge+Radahn"),
  Boss(name: "Magma Wyrm Makar", author: "Elden Ring Wiki", difficulty: 2, excerpt: "Magma Wyrm Makar is a Great Enemy Boss in Elden Ring.", image: "magmawyrmmakar", content: "Makar was once human, but was transformed into a lesser dragon for the sin of Dragon Communion and now guards the Ruin-Strewn Precipice in Liurnia of the Lakes. This is an optional boss as players don't have to defeat it to advance in Elden Ring.", url: "https://eldenring.wiki.fextralife.com/Magma+Wyrm+Makar"),
  Boss(name: "Mimic Tear", author: "Elden Ring Wiki", difficulty: 1, excerpt: "Mimic Tear (known as Stray Mimic Tear during fight at Hidden Path to the Haligtree) is a Boss in Elden Ring.", image: "mimictear", content: "The Mimic Tear is found in Nokron, Eternal City and the Hidden Path to the Haligtree. Its fight is a mirror match as the boss copies your equipment and appearance when fighting you. Mimic Tears are special kinds of Silver Tears that can completely mimic their opponent. They were created by the people of the Eternal Cities, and Mimic Tears in particular were created in an attempt to forge a lord.\nThis is an optional boss, as players don't need to defeat it in order to advance in Elden Ring. However, doing so yields useful Items and Runes. Take note of all the Weapons and Spells you have equipped when spawning the boss in - these are the exact same weapons and spells you'll find yourself faced against. With this in mind, it's possible to unequip all your equipment and spells before the fight starts to force the Mimic Tear to fight with its bare fists. Re-equipping them during the boss fight will not re-equip them for the Mimic Tear. It drops the Silver Tear Mask or Blackflame Monk Amon Ashes when defeated.\nA Mimic Tear can be summoned as a spirit for aid in battle by using the Mimic Tear Ashes.", url: "https://eldenring.wiki.fextralife.com/Mimic+Tear"),
  Boss(name: "Royal Knight Loretta", author: "Elden Ring Wiki", difficulty: 4, excerpt: "Royal Knight Loretta is a Greater Foe Boss in Elden Ring. Royal Knight Loretta is the spirit of a knight riding atop her steed.", image: "loretta", content: "She wields a polearm and utilizes powerful glintstone sorceries to punish would-be trespassers to her domain, the Caria Manor in northern Liurnia of the Lakes. This is an optional boss as players don't need to defeat her to advance in Elden Ring, though they do need to defeat her to reach the Three Sisters and achieve a certain ending.", url: "https://eldenring.wiki.fextralife.com/Royal+Knight+Loretta"),
  Boss(name: "Dragonkin Soldier of Nokstella", author: "Elden Ring Wiki", difficulty: 3, excerpt: "Dragonkin Soldier of Nokstella is a Greater Foe Boss in Elden Ring. This huge, draconic humanoid guards an ancient throne beneath the eternal city of Nokstella.", image: "dragonkin", content: "This Elden Ring Dragonkin Soldier of Nokstella Guide features boss locations, tips, strategies and videos on how to defeat Dragonkin Soldier of Nokstella easily, as well as boss stats and lore for Dragonkin Soldier of Nokstella. Bosses are unique and challenging Enemies that can be encountered all over the Lands Between. Great Enemy bosses can drop unique Spirit Ashes, Weapons, Spells, and other various Items. This is an optional boss, as players don't need to defeat it in order to advance in Elden Ring. However, doing so yields useful items, as well as Runes.", url: "https://eldenring.wiki.fextralife.com/Dragonkin+Soldier+of+Nokstella"),
  Boss(name: "Valiant Gargoyle", author: "Elden Ring Wiki", difficulty: 3, excerpt: "Valiant Gargoyle is a Boss in Elden Ring.", image: "gargoyle", content: "These large stone gargoyles wield various weapons and move with considerable dexterity for their size. This is an optional boss, as players don't need to defeat it in order to advance in Elden Ring.\nBlack Blade Kindred is another variant of this boss.", url: "https://eldenring.wiki.fextralife.com/Valiant+Gargoyle"),
  Boss(name: "Astel Naturalborn of the Void", author: "Elden Ring Wiki", difficulty: 4, excerpt: "Astel, Naturalborn of the Void is a Legend Boss in Elden Ring. This strange alien lifeform is comprised of many-colored star debris which landed in the Lands Between long ago, and is found in the Grand Cloister.", image: "astel", content: "Astel destroyed one of the Eternal Cities and wiped out their sky. This is an optional boss, as players don't need to defeat it in order to advance in Elden Ring. However, it must be defeated to achieve a certain ending.\nAstel, Stars of Darkness is another version of this boss.", url: "https://eldenring.wiki.fextralife.com/Astel+Naturalborn+of+the+Void"),
  Boss(name: "Godskin Noble", author: "Elden Ring Wiki", difficulty: 2, excerpt: "Godskin Noble is a Great Enemy Boss in Elden Ring. These humanoid enemies dress in an armor made from voluminous flaps of skin, wielding rapiers and black flame magic.", image: "godskinnoble", content: "They are optional bosses as they don't need to be defeated to advance in Elden Ring.\nGodskin Noble also appears in the Godskin Duo fight and as a spirit summon in a Spirit-Caller Snail fight.", url: "https://eldenring.wiki.fextralife.com/Godskin+Noble"),
  Boss(name: "Rikard, Lord of Blasphemy", author: "Elden Ring Wiki", difficulty: 3, excerpt: "God-Devouring Serpent and Rykard, Lord of Blasphemy is a two-phase Demigod Boss in Elden Ring. The God-Devouring Serpent is a massive coiled serpent found at the Volcano Manor in Mt. Gelmir, and Rykard, Lord of Blasphemy is its true form that's revealed after the first phase is defeated.", image: "rykard", content: "When Rykard offered himself up to the serpent in a pursuit of immortality, most of his followers turned on him and sought to bring him down with the Serpent-Hunter.\nRykard is an optional boss, and doesn't need to be defeated in order to advance in Elden Ring. However, Rykard is a shardbearer, and two of the five available shardbearers must be defeated before entering Leyndell, Royal Capital.", url: "https://eldenring.wiki.fextralife.com/Rykard,+Lord+of+Blasphemy"),
  Boss(name: "Elemer of the Briar", author: "Elden Ring Wiki", difficulty: 3, excerpt: "Elemer of the Briar is a Great Enemy Boss in Elden Ring.", image: "elemer", content: " Elemer of the Briar is an extremely aggressive human boss and is found in The Shaded Castle in Altus Plateau. This is an optional boss as players don't need to defeat it to advance the plot of the game.", url: "https://eldenring.wiki.fextralife.com/Elemer+of+the+Briar"),
  Boss(name: "Godfrey, First Elden Lord (Golden Shade)", author: "Elden Ring Wiki", difficulty: 3, excerpt: "Godfrey, First Elden Lord (Golden Shade) is a Great Enemy Boss in Elden Ring.", image: "godfreygoldenshade", content: "This is a spectral shade of Godfrey that is encountered in Leyndell, Royal Capital. This is not an optional boss as players must defeat it to advance in Elden Ring.", url: "https://eldenring.wiki.fextralife.com/Godfrey,+First+Elden+Lord+(Golden+Shade)"),
  Boss(name: "Morgott The Omen King", author: "Elden Ring Wiki", difficulty: 4, excerpt: "Morgott, The Omen King, also known as Morgott the Grace Given, is a Demigod Boss in Elden Ring. Morgott is the true identity of Margit, the Fell Omen, and the self-proclaimed 'Last of All Kings'.", image: "morgott", content: "Although he and his twin brother Mohg were imprisoned deep in the Subterranean Shunning-Grounds for being born as Omen royalty, Morgott still loved the Golden Order and defended the capital when his fellow demigods invaded during the Shattering. This is not an optional boss as players must defeat him to advance in Elden Ring.", url: "https://eldenring.wiki.fextralife.com/Morgott+the+Omen+King"),
  Boss(name: "Mohg, The Omen", author: "Elden Ring Wiki", difficulty: 3, excerpt: "Mohg, the Omen is a Great Enemy Boss in Elden Ring. This powerful Omen has royal blood and communes with an outer god known as the Mother of Truth.", image: "mohgtheomen", content: "This is an optional boss as players do not need to defeat it to advance in Elden Ring, but either it or the Valiant Gargoyle duo must be defeated to enter Deeproot Depths and achieve a certain ending.", url: "https://eldenring.wiki.fextralife.com/Mohg,+the+Omen"),
  Boss(name: "Comander Niall", author: "Elden Ring Wiki", difficulty: 4, excerpt: "Commander Niall is a Great Enemy Boss in Elden Ring. Commander Niall is found in Castle Sol in Mountaintops of the Giants.", image: "niall", content: "This is an optional boss, as players don't need to defeat it in order to advance in Elden Ring. However, he must be defeated before entering Consecrated Snowfield.", url: "https://eldenring.wiki.fextralife.com/Commander+Niall"),
  Boss(name: "Fire Giant", author: "Elden Ring Wiki", difficulty: 3, excerpt: "Fire Giant is a Legend Boss in Elden Ring.", image: "firegiant", content: "The last known survivor of the war against the giants, this massive humanoid has a face on its chest and is found in the Mountaintops of the Giants. This is not an optional boss as players must defeat this foe in order to advance in Elden Ring.", url: "https://eldenring.wiki.fextralife.com/Fire+Giant"),
  Boss(name: "Loretta, Knight of the haligtree", author: "Elden Ring Wiki", difficulty: 3, excerpt: "Loretta, Knight of the Haligtree is a Greater Foe Boss in Elden Ring. This proud knight was previously in service to the Carian royal family.", image: "lorettahaligtree", content: "This is an optional boss as players don't need to defeat her to advance in Elden Ring, though they do need to defeat her to reach Elphael, Brace of the Haligtree and face Malenia, Blade of Miquella.\nAt some point, Loretta set out on a journey to find a safe haven for the Albinauric people, until she finally came across Miquella's Haligtree. She is rumored to be an Albinauric herself. The blue glintstone of the war sickle she was given for being the personal guard of the Carian family has been replaced with the unalloyed gold often attributed to the young god Miquella.", url: "https://eldenring.wiki.fextralife.com/Loretta,+Knight+of+the+Haligtree"),
  Boss(name: "Malenia Blade of Miquella", author: "Elden Ring Wiki", difficulty: 5, excerpt: "Malenia, Blade of Miquella and Malenia, Goddess of Rot is two-phase a Demigod Boss in Elden Ring.", image: "malenia", content: "She's the twin of Miquella, the most powerful of the Empyreans, and gained renown for her legendary battle against Starscourge Radahn during the Shattering, in which she unleashed the power of the Scarlet Rot and reduced Caelid to ruins.\nThis is an optional boss, as players do not need to defeat it in order to advance in Elden Ring.", url: "https://eldenring.wiki.fextralife.com/Malenia+Blade+of+Miquella"),
  Boss(name: "Malenia Blade of Miquella", author: "Elden Ring Wiki", difficulty: 5, excerpt: "Malenia, Blade of Miquella and Malenia, Goddess of Rot is two-phase a Demigod Boss in Elden Ring.", image: "malenia", content: "She's the twin of Miquella, the most powerful of the Empyreans, and gained renown for her legendary battle against Starscourge Radahn during the Shattering, in which she unleashed the power of the Scarlet Rot and reduced Caelid to ruins.\nThis is an optional boss, as players do not need to defeat it in order to advance in Elden Ring.", url: "https://eldenring.wiki.fextralife.com/Malenia+Blade+of+Miquella"),
  Boss(name: "Godskin Duo", author: "Elden Ring Wiki", difficulty: 4, excerpt: "Godskin Duo is a Boss in Elden Ring.", image: "godskinduo", content: "In this dual boss fight, you'll have to fight against a Godskin Apostle and a Godskin Noble simultaneously, as each one resurrects the other. This is not an optional boss as players must defeat it in order to advance in Elden Ring.", url: "https://eldenring.wiki.fextralife.com/Godskin+Duo"),
  Boss(name: "Dragonlord Placidusax", author: "Elden Ring Wiki", difficulty: 4, excerpt: "Dragonlord Placidusax is a Legend Boss in Elden Ring. This massive, two-headed dragon is found in Crumbling Farum Azula.", image: "placidusax", content: "He reigned as the current Elden Lord at some time before the reign of Marika and the Golden Order and presumably ruled alongside his god, who later fled. The Old Lord's Talisman suggests that Placidusax had at least two more heads that had been removed by the time the Tarnished reaches him.\nThis is an optional boss, as players don't need to defeat it in order to advance in Elden Ring.", url: "https://eldenring.wiki.fextralife.com/Dragonlord+Placidusax"),
  Boss(name: "Maliketh, The Black Blade", author: "Elden Ring Wiki", difficulty: 5, excerpt: "Beast Clergyman and Maliketh, The Black Blade is a two-phase Legend Boss in Elden Ring. The Beast Clergyman is found at the end of Crumbling Farum Azula and is revealed to be Maliketh, the Black Blade once you deal enough damage to him.", image: "maliketh", content: "Similar to how Blaidd is to Ranni, Maliketh is Queen Marika's shadow-bound beast. He was tasked to guard the Rune of Death, but his failure to do so led to the Night of the Black Knives. In order for this to never happen again, he imbued the rune into his very flesh.\nThis is not an optional boss, as players must defeat it to advance to Leyndell, Ashen Capital and finish the game.\nGurranq, Beast Clergyman is an NPC variant of the first phase of this boss.", url: "https://eldenring.wiki.fextralife.com/Maliketh,+the+Black+Blade"),
  Boss(name: "Lichdragon Fortissax", author: "Elden Ring Wiki", difficulty: 5, excerpt: "Lichdragon Fortissax is a Legend Boss in Elden Ring. This massive four-winged black dragon wields powerful lightning attacks and is found in Deeproot Depths.", image: "fortissax", content: "During the War of the Ancient Dragons, where the forces of Leyndell battled against the ancient dragons, Godwyn befriended Fortissax. After his death, Fortissax struggled to stave off the death blight that afflicted Godwyn, and was later corrupted by it. This is an optional boss, and doesn't need to be defeated in order to advance in Elden Ring. However, it must be defeated to achieve a certain ending.\nThis boss is missable if the player kills Fia before the end of her quest.\nAncient Dragon Lansseax is another variant of this boss. Farum Azula Dragon is the normal enemy form of this boss.", url: "https://eldenring.wiki.fextralife.com/Lichdragon+Fortissax"),
  Boss(name: "Mohg, Lord of Blood", author: "Elden Ring Wiki", difficulty: 5, excerpt: "Mohg, Lord of Blood is a Demigod Boss in Elden Ring. This Omen demigod specializes in blood magic.", image: "mohglordofblood", content: "Unlike his twin Morgott, Mohg fully embraced his accursed Omen blood and was able to use it to wield bloodflame magic after encountering the Formless Mother. Though he himself is not an Empyrean, he hopes to rise up to king consort by raising Miquella up to godhood and becoming his consort.\nMohg is an optional boss, and doesn't need to be defeated to advance Elden Ring's main storyline. However, he is a shardbearer, and two of the five available shardbearers must be defeated before entering Leyndell, Royal Capital. In addition, Mohg must be defeated to unlock the Shadow of the Erdtree expansion.\nMohg, the Omen is another variant of this boss.", url: "https://eldenring.wiki.fextralife.com/Mohg,+Lord+of+Blood"),
  Boss(name: "Godfrey, First Elden Lord", author: "Elden Ring Wiki", difficulty: 4, excerpt: "Godfrey, First Elden Lord and Hoarah Loux, Warrior is a two-phase Legend Boss in Elden Ring. Godfrey was Queen Marika's first consort, and thus the first Elden Lord of the Lands Between", image: "godfrey", content: "Before earning this title, he was known as Hoarah Loux, the chieftain of the badlands and a bloodthirsty warrior. Godfrey took the Beast Regent Serosh upon his back after committing to his role as a Lord in order to suppress his violent urges. After fighting countless wars, Marika deprived him and his warriors of their grace, marking them as the first Tarnished.\nThis is not an optional boss, as players must defeat it to advance in Elden Ring.\nGodfrey, First Elden Lord (Golden Shade) is another variant of this boss.", url: "https://eldenring.wiki.fextralife.com/Godfrey,+First+Elden+Lord")
    ]

#endif

